hytale.wizard.project.name=Hytale Plugin
hytale.wizard.group.title=Hytale Settings
hytale.wizard.field.plugin.name=Plugin name:
hytale.wizard.field.package=Package:
hytale.wizard.field.patchline=Patchline:
hytale.wizard.field.hytale.version=Hytale version:
